//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buran.Core.MvcLibrary.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buran.Core.MvcLibrary.Resource.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; kayıdını silmek istediğinizden emin misiniz?.
        /// </summary>
        internal static string AskDelete {
            get {
                return ResourceManager.GetString("AskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İle Başlayan.
        /// </summary>
        internal static string Baslayan {
            get {
                return ResourceManager.GetString("Baslayan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyük Eşittir.
        /// </summary>
        internal static string BuyukEsit {
            get {
                return ResourceManager.GetString("BuyukEsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyüktür.
        /// </summary>
        internal static string Buyuktur {
            get {
                return ResourceManager.GetString("Buyuktur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtreyi Temizle.
        /// </summary>
        internal static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Filtre:.
        /// </summary>
        internal static string CurrentFilter {
            get {
                return ResourceManager.GetString("CurrentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşittir.
        /// </summary>
        internal static string Esit {
            get {
                return ResourceManager.GetString("Esit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        internal static string ExportExcelText {
            get {
                return ResourceManager.GetString("ExportExcelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dışa Aktar.
        /// </summary>
        internal static string ExportText {
            get {
                return ResourceManager.GetString("ExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçeren.
        /// </summary>
        internal static string Iceren {
            get {
                return ResourceManager.GetString("Iceren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçük Eşittir.
        /// </summary>
        internal static string KucukEsit {
            get {
                return ResourceManager.GetString("KucukEsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küçüktür.
        /// </summary>
        internal static string Kucuktur {
            get {
                return ResourceManager.GetString("Kucuktur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt: {0}-{1}/{2}.
        /// </summary>
        internal static string PagerDesc {
            get {
                return ResourceManager.GetString("PagerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt: 0.
        /// </summary>
        internal static string PagerDesc_No {
            get {
                return ResourceManager.GetString("PagerDesc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boyut: .
        /// </summary>
        internal static string PageSizeKeyword {
            get {
                return ResourceManager.GetString("PageSizeKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
    }
}
